const GET_PRICES = 'GET_PRICES';
const GET_UI = 'GET_UI';
const CHANGE_VIEW = 'CHANGE_VIEW';
const TOGGLE_CURRENCY = 'TOGGLE_CURRENCY';
const SORT = 'SORT';
const CURRENCIES_NONE  = 'CURRENCIES_NONE';
const CURRENCIES_ALL  = 'CURRENCIES_ALL';

export {
    GET_PRICES,
    GET_UI,
    CHANGE_VIEW,
    TOGGLE_CURRENCY,
    SORT,
    CURRENCIES_NONE,
    CURRENCIES_ALL
};